"""extract_outlines.py — glyph outlines out of Figma "export as SVG" files of TEXT nodes → outlines.js.

Why: light-on-dark browser text renders ~10 % heavier than Figma's (grayscale AA gamma, no Chrome switch
changes it — quirk #192). Figma's own outlines, drawn as SVG paths, rasterise like Figma.

Export each TEXT node with download_assets(defaultFormat 'svg'); Figma puts the node on its page and frame
backgrounds, with the SVG origin at the text's ink bbox and the frame at translate(-fx, -fy) (on its
clipPath, or on the body rect when there is no clip). We keep the path(s) that carry an id (the layer
name) and store their origin relative to the text-node box.

    python extract_outlines.py outlines.json lib/outlines.js
    outlines.json: { "key": { "svg": "assets/txt-x.svg", "x": 60, "y": 783, "bodyX": 0.5283 }, … }
      x, y   the TEXT node box (frame coordinates, from the layer dump)
      bodyX  x of the frame's body (only used when the export has no frame clipPath)
Use: Fig.text(parent, { …, outline: OUTLINES.key, color: [r,g,b] }) — same props as live text.
"""
import re, os, sys, json

def origin(svg, body_x):
    m = re.search(r'<clipPath id="[^"]+">\s*<rect[^>]*transform="translate\(([-\d.]+) ([-\d.]+)\)"', svg)
    if m:
        return -float(m.group(1)), -float(m.group(2))
    m = re.search(r'<rect width="[\d.]+" height="[\d.]+" transform="translate\(([-\d.]+) ([-\d.]+)\)" fill="#[0-9A-Fa-f]{6}"/>', svg)
    if not m:
        raise SystemExit("no frame clipPath / body rect found — cannot place the outline")
    return body_x - float(m.group(1)), -float(m.group(2))

def main():
    cfg_path, out_path = sys.argv[1], sys.argv[2]
    cfg = json.load(open(cfg_path, encoding="utf-8"))
    base = os.path.dirname(os.path.abspath(cfg_path))
    out = {}
    for key, c in cfg.items():
        svg = open(os.path.join(base, c["svg"]), encoding="utf-8").read()
        fx, fy = origin(svg, c.get("bodyX", 0))
        texts = [(i, d, f) for (i, d, f) in re.findall(r'<path id="([^"]*)" d="([^"]+)" fill="([^"]+)"/>', svg) if i]
        if not texts:
            raise SystemExit("no text path in " + c["svg"])
        out[key] = {"d": " ".join(t[1] for t in texts), "fill": texts[0][2], "ox": round(fx - c["x"], 4), "oy": round(fy - c["y"], 4)}
        print(key, "origin", (fx, fy), "rel", out[key]["ox"], out[key]["oy"], "paths", len(texts))
    js = "// outlines.js — GENERATED by extract_outlines.py from Figma SVG exports of TEXT nodes.\nwindow.OUTLINES = " + json.dumps(out, ensure_ascii=True) + ";\n"
    open(out_path, "w", encoding="utf-8").write(js)
    print("written", out_path)

if __name__ == "__main__":
    main()
