// build-tokens.js — emit the generated token files from brand/cloudru-motion-tokens.json.
//
//   node scripts/build-tokens.js          # write scripts/lib/tokens.jsx, html/engine/tokens.js, html/engine/tokens.css
//   node scripts/build-tokens.js --check  # exit 1 if any generated file is stale (used by tests)
//
// The JSON is the single source of truth for BOTH engines. Never hand-edit the outputs.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'brand', 'cloudru-motion-tokens.json');

function hexToRgb01(hex) {
  const h = hex.replace('#', '');
  const n = parseInt(h, 16);
  const r = ((n >> 16) & 255) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  return [round5(r), round5(g), round5(b)];
}
function round5(x) { return Math.round(x * 100000) / 100000; }
function ident(s) { return s.replace(/[^a-zA-Z0-9_]/g, '_'); }

// Strip "_note"/"_rule" style keys so the generated code carries data only.
function stripMeta(obj) {
  if (Array.isArray(obj)) return obj.map(stripMeta);
  if (obj && typeof obj === 'object') {
    const out = {};
    Object.keys(obj).forEach((k) => { if (k[0] !== '_') out[k] = stripMeta(obj[k]); });
    return out;
  }
  return obj;
}

function buildJsx(t) {
  const L = [];
  L.push('// GENERATED by scripts/build-tokens.js from brand/cloudru-motion-tokens.json - do not edit.');
  L.push('// ES3-safe: plain vars, no trailing commas, no reserved words as keys.');
  L.push('var CR = {};');
  L.push('CR.COLOR = {};');
  Object.keys(t.color.base).forEach((k) => {
    const c = t.color.base[k];
    L.push('CR.COLOR.' + ident(k).toUpperCase() + ' = [' + hexToRgb01(c.hex).join(', ') + '];  // ' + c.hex);
  });
  L.push('CR.COLOR.ARROW = [' + hexToRgb01(t.color.arrow.light).join(', ') + '];  // ' + t.color.arrow.light);
  L.push('CR.COLOR_EXT = {};');
  Object.keys(t.color.extended).forEach((k) => {
    if (k[0] === '_') return;
    const c = t.color.extended[k];
    L.push('CR.COLOR_EXT.' + ident(k).toUpperCase() + ' = [' + hexToRgb01(c.hex).join(', ') + '];');
    L.push('CR.COLOR_EXT.' + ident(k).toUpperCase() + '_MUTED = [' + hexToRgb01(c.muted).join(', ') + '];');
  });
  L.push('CR.HEX = {};');
  Object.keys(t.color.base).forEach((k) => {
    L.push('CR.HEX.' + ident(k).toUpperCase() + ' = "' + t.color.base[k].hex + '";');
  });
  L.push('CR.FONT = {};');
  Object.keys(t.type.ae_postscript).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.FONT.' + ident(k).toUpperCase() + ' = "' + t.type.ae_postscript[k] + '";');
  });
  L.push('CR.FONT.FALLBACK = "Verdana";');
  L.push('CR.FONT.FALLBACK_BOLD = "Verdana-Bold";');
  L.push('CR.TYPE = {};');
  Object.keys(t.type.scale_1080).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.TYPE.' + ident(k).toUpperCase() + ' = ' + t.type.scale_1080[k] + ';');
  });
  L.push('CR.LEADING = {};');
  Object.keys(t.type.leading).forEach((k) => { L.push('CR.LEADING.' + ident(k).toUpperCase() + ' = ' + t.type.leading[k] + ';'); });
  L.push('CR.TRACKING = {};  // AE units (1/1000 em)');
  Object.keys(t.type.tracking).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.TRACKING.' + ident(k).toUpperCase() + ' = ' + Math.round(t.type.tracking[k] * 1000) + ';');
  });
  L.push('CR.EASE = {};  // cubic-bezier [x1,y1,x2,y2]; use M.bezierEase(prop,k,CR.EASE.ENTER)');
  Object.keys(t.ease).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.EASE.' + ident(k).toUpperCase() + ' = [' + t.ease[k].bezier.join(', ') + '];');
  });
  L.push('CR.INFLUENCE = {};  // zero-speed shorthand [startOut, landIn]');
  Object.keys(t.ease).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.INFLUENCE.' + ident(k).toUpperCase() + ' = [' + t.ease[k].ae_influence.join(', ') + '];');
  });
  L.push('CR.MS = {};  // durations in ms; frames via M.f(ms) once M.setComp() knows the fps');
  Object.keys(t.duration_ms).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.MS.' + ident(k).toUpperCase() + ' = ' + t.duration_ms[k] + ';');
  });
  L.push('CR.STAGGER_MS = {};');
  Object.keys(t.stagger_ms).forEach((k) => {
    if (k[0] === '_') return;
    L.push('CR.STAGGER_MS.' + ident(k).toUpperCase() + ' = ' + t.stagger_ms[k] + ';');
  });
  L.push('CR.TRAVEL = {};  // px at 1080p');
  Object.keys(t.travel_px_1080).forEach((k) => {
    if (k[0] === '_' || typeof t.travel_px_1080[k] !== 'number') return;
    L.push('CR.TRAVEL.' + ident(k).toUpperCase() + ' = ' + t.travel_px_1080[k] + ';');
  });
  L.push('CR.GEO = {};');
  Object.keys(t.geometry).forEach((k) => {
    const v = t.geometry[k];
    const lit = Array.isArray(v) ? '[' + v.join(', ') + ']' : (typeof v === 'string' ? '"' + v + '"' : String(v));
    L.push('CR.GEO.' + ident(k).toUpperCase() + ' = ' + lit + ';');
  });
  L.push('CR.FORMAT = {};');
  Object.keys(t.format).forEach((k) => {
    if (k[0] === '_') return;
    const f = t.format[k];
    L.push('CR.FORMAT["' + k + '"] = { w: ' + f.w + ', h: ' + f.h + ', fps: ' + f.fps + ', scale: ' + f.scale +
      ', margin: ' + f.margin + ', safeTitle: ' + f.safe_title + ' };');
  });
  return L.join('\n') + '\n';
}

function buildJs(t) {
  const data = stripMeta(t);
  const body = JSON.stringify(data, null, 2);
  return '// GENERATED by scripts/build-tokens.js from brand/cloudru-motion-tokens.json - do not edit.\n' +
    '(function (root, factory) {\n' +
    "  if (typeof module === 'object' && module.exports) module.exports = factory();\n" +
    '  else root.MotionTokens = factory();\n' +
    '})(typeof self !== \'undefined\' ? self : this, function () {\n' +
    '  return ' + body.replace(/\n/g, '\n  ') + ';\n' +
    '});\n';
}

function buildCss(t) {
  const L = [];
  L.push('/* GENERATED by scripts/build-tokens.js from brand/cloudru-motion-tokens.json - do not edit. */');
  L.push(':root {');
  Object.keys(t.color.base).forEach((k) => { L.push('  --cr-' + k + ': ' + t.color.base[k].hex + ';'); });
  L.push('  --cr-arrow: ' + t.color.arrow.light + ';');
  Object.keys(t.color.extended).forEach((k) => {
    if (k[0] === '_') return;
    L.push('  --cr-ext-' + k + ': ' + t.color.extended[k].hex + ';');
    L.push('  --cr-ext-' + k + '-muted: ' + t.color.extended[k].muted + ';');
  });
  L.push('  --cr-font: "' + t.type.family + '", ' + t.type.fallback.join(', ') + ';');
  Object.keys(t.type.scale_1080).forEach((k) => {
    if (k[0] === '_') return;
    L.push('  --cr-type-' + k.replace(/_/g, '-') + ': ' + t.type.scale_1080[k] + 'px;');
  });
  Object.keys(t.type.leading).forEach((k) => { L.push('  --cr-leading-' + k.replace(/_/g, '-') + ': ' + t.type.leading[k] + ';'); });
  Object.keys(t.type.tracking).forEach((k) => {
    if (k[0] === '_') return;
    L.push('  --cr-tracking-' + k.replace(/_/g, '-') + ': ' + t.type.tracking[k] + 'em;');
  });
  Object.keys(t.ease).forEach((k) => {
    if (k[0] === '_') return;
    L.push('  --cr-ease-' + k + ': cubic-bezier(' + t.ease[k].bezier.join(', ') + ');');
  });
  Object.keys(t.duration_ms).forEach((k) => {
    if (k[0] === '_') return;
    L.push('  --cr-ms-' + k.replace(/_/g, '-') + ': ' + t.duration_ms[k] + 'ms;');
  });
  L.push('  --cr-module: ' + t.geometry.micro_module + 'px;');
  L.push('  --cr-radius: ' + t.geometry.corner_radius + 'px;');
  L.push('}');
  return L.join('\n') + '\n';
}

function outputs(t) {
  return {
    [path.join(ROOT, 'scripts', 'lib', 'tokens.jsx')]: buildJsx(t),
    [path.join(ROOT, 'html', 'engine', 'tokens.js')]: buildJs(t),
    [path.join(ROOT, 'html', 'engine', 'tokens.css')]: buildCss(t)
  };
}

module.exports = { buildJsx, buildJs, buildCss, hexToRgb01, outputs };

if (require.main === module) {
  const t = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  const outs = outputs(t);
  const check = process.argv.indexOf('--check') !== -1;
  let stale = 0;
  Object.keys(outs).forEach((p) => {
    const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (check) {
      if (cur !== outs[p]) { stale += 1; console.error('STALE: ' + path.relative(ROOT, p)); }
    } else {
      fs.mkdirSync(path.dirname(p), { recursive: true });
      fs.writeFileSync(p, outs[p]);
      console.log('wrote ' + path.relative(ROOT, p));
    }
  });
  if (check) { console.log(stale ? stale + ' stale file(s)' : 'tokens up to date'); process.exit(stale ? 1 : 0); }
}
